---
- name: systemd start nfs container
  systemd:
    name: ceph-nfs@{{ ceph_nfs_service_suffix | default(ansible_hostname) }}
    state: started
    enabled: yes
    daemon_reload: yes
  when:
    - containerized_deployment
    - ceph_nfs_enable_service